#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Billingares.Api.gRPC/Billingares.Api.gRPC.csproj", "Billingares.Api.gRPC/"]
RUN dotnet restore "Billingares.Api.gRPC/Billingares.Api.gRPC.csproj"
COPY . .
WORKDIR "/src/Billingares.Api.gRPC"
RUN dotnet build "Billingares.Api.gRPC.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Billingares.Api.gRPC.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Billingares.Api.gRPC.dll"]