FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Billingares.Api.REST/Billingares.Api.REST.csproj", "Billingares.Api.REST/"]
COPY ["Billingares.Api/Billingares.Api.csproj", "Billingares.Api/"]
COPY ["Billingares.Base/Billingares.Base.csproj", "Billingares.Base/"]
COPY ["Billingares.Backend/Billingares.Backend.csproj", "Billingares.Backend/"]
COPY ["Ujeby.Api.Base/Ujeby.Api.Base.csproj", "Ujeby.Api.Base/"]
RUN dotnet restore "Billingares.Api.REST/Billingares.Api.REST.csproj"
COPY . .
WORKDIR "/src/Billingares.Api.REST"
RUN dotnet build "Billingares.Api.REST.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Billingares.Api.REST.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Billingares.Api.REST.dll"]