FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Billingares.WebApi/Billingares.WebApi.csproj", "Billingares.WebApi/"]
COPY ["Billingares.Api.Client/Billingares.Api.Client.csproj", "Billingares.Api.Client/"]
COPY ["Billingares.Base/Billingares.Base.csproj", "Billingares.Base/"]
RUN dotnet restore "Billingares.WebApi/Billingares.WebApi.csproj"
COPY . .
WORKDIR "/src/Billingares.WebApi"
RUN dotnet build "Billingares.WebApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Billingares.WebApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Billingares.WebApi.dll"]